resources:
    App\Entity\Greeting: ~
    App\Entity\Book:
        attributes:
            filters: ['book.search_filter']
            normalization_context:
                groups: ['book:list']
            denormalization_context:
                groups: ['book:write']
        itemOperations:
            get:
                method: 'GET'
                normalization_context:
                    groups: ['book:read']
            put:
                method: 'PUT'
            delete:
                method: 'DELETE'
        properties:
            reviews:
                subresource:
                    resourceClass: App\Entity\Review
                    maxDepth: 1
                    collection: true
    App\Entity\Author:
        attributes:
            order:
                lastname: DESC
                firstname: ASC
        properties:
            books:
                subresource:
                    resourceClass: App\Entity\Book
                    maxDepth: 1
                    collection: true
    App\Entity\Review: ~
